TYPE_METADATA_FIELD = '_type'
SELF_METADATA_FIELD = '_self'
SUPER_METADATA_FIELD = '_super'

LIST_TYPE = 'list'
SHOULD_NOT_BE_EXPANDED_MARK = 'as-is'
SHOULD_BE_EXPANDED_MARK = 'expand'

DEFAULT_CONFIG_NAME_KEY = 'name'
